apiVersion: v1
kind: Service
metadata:
  name: lobby-service
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  selector:
    app: lobby
  ports:
    - protocol: TCP
      port: 30000
      targetPort: 30000
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: lobby-deployment
  namespace: default
  labels:
    app: lobby
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lobby
  template:
    metadata:
      labels:
        app: lobby
    spec:
      tolerations:
      - key: "key"
        operator: "Equal"
        value: "geeks"
        effect: "NoSchedule"
      containers:
      - name: lobby-container
        image: 756266714368.dkr.ecr.ap-northeast-2.amazonaws.com/lobby:35
        ports:
        - containerPort: 30000     # lobby-sub server port

